language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '7.0'
  - '7.1'

matrix:
  fast_finish: true

before_script:
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script: vendor/bin/phpunit --color tests

after_success:
  - travis_retry php vendor/bin/coveralls


