language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - '5.0.1'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

before_script:
  - composer install

script: ./vendor/bin/phpunit --colors tests

matrix:
  fast_finish: true

notifications:
  on_success: never
  on_failure: change

